version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: blue-web
    ports:
      - "8081:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    command: >
      /bin/sh -c "
        apk add --no-cache curl &&
        nginx -g 'daemon off;'
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3
